elasticsearch:
  build: dockerfiles/elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  build: dockerfiles/logstash
  ports:
    - "5000:5000"
    - "5000:5000/udp"
  environment:
    #LOGSPOUT: ignore 
  links:
    - elasticsearch:elasticsearch
  command: -f /etc/logstash.conf.sample
kibana:
  build: dockerfiles/kibana
  ports:
    - "80:80"
logspout:
  build: dockerfiles/logspout
  net: container:logstash
  environment:
    DEBUG: true
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  command: syslog://localhost:5000
